org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=384m
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=out-of-process
systemProp.org.gradle.wrapper.timeout=300000

# Optimization for faster builds
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=true
org.gradle.vfs.watch=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
