create table if not exists public.profiles (
  user_id text primary key,
  email text,
  username text,
  is_premium boolean not null default false,
  plan_type text,
  subscription_id text,
  subscription_status text,
  premium_expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.premium_members (
  user_id text primary key,
  email text,
  username text,
  plan_type text not null default 'lifetime',
  subscription_id text,
  subscription_status text not null default 'active',
  premium_expires_at timestamptz,
  order_id text,
  payment_id text,
  amount_inr integer not null default 299,
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  txnid text not null unique,
  amount integer not null,
  status text not null,
  provider_reference_id text,
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.premium_members enable row level security;
alter table public.payment_transactions enable row level security;
